version: "3.9"
services:
  db:
    image: postgres:9
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "dbvolume:/var/lib/postgresql/data/pgdata"
  adminer:
    image: adminer
    ports:
      - 8081:8080
volumes:
  dbvolume:
