
spring:
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: admin
  flyway:
    url: "jdbc:postgresql://localhost:5432/postgres"
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
